fun main(){
    print("Student Enrollment Number:")
    var string1 = readLine()
    print("Student Name:")
    var string2 = readLine()
    print("Student Branch:")
    var string3 = readLine()
    print("Student Class:")
    var string4 = readLine()
    print("Student Batch:")
    var string5 = readLine()
    print("Student College name:")
    var string6 = readLine()
    print("Student University name:")
    var string7 = readLine()
    print("Student Age:")
    var string8 = readLine()
    println("********************")
    println("Student's Data:")
    println("Enrollment No.:$string1")
    println("Name:$string2")
    println("Age:$string8")
    println("Branch:$string3")
    println("Class:$string4")
    println("Batch:$string5")
    println("College Name:$string6")
    println("University Name:$string7")
}
